
title: Brian Mukindi Blog
description: Learning to build professional blogs with GitHub Pages
url: https://brianmukindi.github.io

markdown: kramdown
permalink: /:2025/:January/:Thursday/:Automation projects/
